### ISSUE TITLE
In case mongodb 4.2, the following error occurs

### ISSUE THREAD

**Issue by rafael-0317** [MaBeuLux88/mongodb-4.0-demos#4]
hi, 
In case mongodb 4.2, the following error occurs,
What is the problem?

```
Database state:
Product{id='chocolate', stock=1, price=3}
Cart{id='Nofar', items=[Item{productId=chocolate, quantity=2, price=3}]}

Exception in thread "main" com.mongodb.MongoWriteException: Document failed validation
        at com.mongodb.client.internal.MongoCollectionImpl.executeSingleWriteRequest(MongoCollectionImpl.java:1015)
        at com.mongodb.client.internal.MongoCollectionImpl.executeUpdate(MongoCollectionImpl.java:992)
        at com.mongodb.client.internal.MongoCollectionImpl.updateOne(MongoCollectionImpl.java:589)
        at com.mongodb.client.internal.MongoCollectionImpl.updateOne(MongoCollectionImpl.java:582)
        at com.mongodb.Transactions.removingChocolateFromStock(Transactions.java:130)
        at com.mongodb.Transactions.ClientWantsExtraChocolatesInTransactionThenCommitOrRollback(Transactions.java:104)
        at com.mongodb.Transactions.demo(Transactions.java:94)
        at com.mongodb.Transactions.main(Transactions.java:53)
```

**Comment by MaBeuLux88** [comment]
Hi @EthanHyeongHwaPark,

This repo was initially written when MDB 4.2 wasn't released. I did this when 4.0 was released so 2 years ago now.
I updated this code so it now also works with MongoDB 4.2 and 4.4.

Apparently in MDB 4.2, they changed the exception raised when a transaction fails and needs to rollback. 

In my exemple, the change streams creates a JSON Schema to prevent the stock of beers from ever being negative - So it prevents me from selling more beers than I own. 

This is the expected output: 

```
Database state:
Product{id='beer', stock=1, price=3}
Cart{id='Alice', items=[Item{productId=beer, quantity=4, price=3}]}

Sleeping 3 seconds...

######### WITH TRANSACTION #########
Alice wants 2 extra beers.
This time we do not have enough beers in stock so the transaction will rollback.
---------------------------------------------------------------------------
Updating Alice cart : adding 2 beers.
Sleeping 3 seconds...
Trying to update beer stock : -2 beers.
#####   MongoCommandException  #####
##### STOCK CANNOT BE NEGATIVE #####
####### ROLLBACK TRANSACTION #######
####################################

Database state:
Product{id='beer', stock=1, price=3}
Cart{id='Alice', items=[Item{productId=beer, quantity=4, price=3}]}
```

They changed the exception raised when I violate this JSON Schema constraint from `MongoCommandException` to `MongoWriteException` apparently. 

I updated the code so both exceptions are catch now. 

```
catch (MongoCommandException | MongoWriteException e)
```

I hope this help :-) !

**Comment by rafael-0317** [comment]
thanks a lot!
